controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    # dodanie prefiksu języka do tras kontrolerów
    prefix: /{_locale}
    defaults:
        _locale: pl
    requirements:
        _locale: pl|en

# przekierowanie /app/ na /app/pl/recipe/
root_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /pl/recipe
        permanent: false